### Create a random user
POST {{host}}/api/1.0/users:createRandom

### Create a user
POST {{host}}/api/1.0/users
Content-Type: application/json

{
  "firstName": "Cheeristian",
  "lastName": "Luzzetti",
  "email": "christian.luzzetti@gmail.com"
}

### Get user details
GET {{host}}/api/1.0/users/2d1a5873-1f09-4043-aaa9-60ce565ef454

### List users
GET {{host}}/api/1.0/users